// InstructRAM — Simulation instruction RAM placeholder
// Auto-generated by c_build/bin_to_verilog_para.py.
// This is a stub; the real content is generated during firmware build.
module InstructRAM;
  // Placeholder — replace with generated content from c_build
endmodule
