#!/usr/bin/env python3
"""
bin_to_verilog_para.py — Convert padded firmware binary to Verilog `define parameters
for synthesis-time instruction RAM initialization.

Usage: python3 bin_to_verilog_para.py <firmware_pads.bin> <output.v> <bin_size_bytes>
Example: python3 bin_to_verilog_para.py out/firmware_pads.bin ../rtl/InstructRAM.v 16384
"""

import sys
import math
import pathlib


def bin_to_verilog(bin_file: pathlib.Path, verilog_file: pathlib.Path,
                   bin_size: int, param_name: str = "Instruct") -> None:
    data = bin_file.read_bytes()

    with verilog_file.open('w', encoding='ascii') as f:
        f.write("// params.v - Auto-generated by bin_to_verilog_para.py\n")
        f.write("`ifndef PARAMS_V\n")
        f.write("`define PARAMS_V\n")
        f.write(f"`define {param_name} ")

        # Total bit width
        bin_size_bits = bin_size * 8
        f.write(f"{bin_size_bits}")

        # Hex data (byte-reversed per 32-bit word)
        f.write("'h")
        reversed_data = []
        for i in range(0, len(data), 4):
            chunk = data[i:i+4]
            reversed_chunk = chunk[::-1]  # big-endian → little-endian
            reversed_data.append(''.join(f'{byte:02X}' for byte in reversed_chunk))
        f.write(''.join(reversed_data) + "\n")

        # Address width
        addr_bits = int(math.log2(bin_size // 4))
        f.write(f"`define instr_AddrBits {addr_bits}\n")
        f.write("`endif\n")

    print(f"  Verilog generated: {bin_size * 8}-bit `define, "
          f"addr_bits={addr_bits}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python3 bin_to_verilog_para.py <input.bin> <output.v> <bin_size_bytes>")
        sys.exit(1)

    input_bin = pathlib.Path(sys.argv[1])
    output_v = pathlib.Path(sys.argv[2])
    bin_size = int(sys.argv[3])

    if not input_bin.exists():
        print(f"Error: input file not found: {input_bin}")
        sys.exit(1)

    bin_to_verilog(input_bin, output_v, bin_size)
