#===================================================================
# timing.xdc — Xilinx XC7A35T-FGG484 timing constraints
#===================================================================
#
# Clock architecture:
#   clk_50m_in       (50MHz,  input) → MMCM → c0_pll_50m   (50MHz,  system)
#                                            → c1_pll_50m   (125MHz, MAC/pkt)
#                                            → c2_pll_50m   (200MHz, IDELAY/SFP)
#   rgmii_rxc        (125MHz, input,  RGMII RX clock from PHY)
#   rgmii_txc        (125MHz, output, RGMII TX clock via ODDR)
#   gtrefclk_p/n     (125MHz, input,  GT reference clock)
#   sgmii_userclk2   (125MHz, gen'd,  SGMII core clock from GT MMCM)
#   sgmii_userclk    (62.5MHz, gen'd,  SGMII user clock)
#
# NOTE: MMCM output clocks are auto-derived by Vivado from the PLL IP
#   (g_clk_pll.u_pll). Vivado names them after the PLL primitive ports:
#     c0_pll_50m  (50MHz)   — from mmcm_adv_inst/CLKOUT0
#     c1_pll_50m  (125MHz)  — from mmcm_adv_inst/CLKOUT1
#     c2_pll_50m  (200MHz)  — from mmcm_adv_inst/CLKOUT2
#   The RTL wire names (clk_50m/clk_125m/clk_200m) are NOT preserved
#   as net names after synthesis, so get_nets clk_50m returns empty.
#
# CDC strategy: Use explicit set_false_path for all async clock pairs.
#   set_clock_groups -asynchronous is also applied as a fallback, but
#   explicit false paths are more reliable when auto-derived clock
#   names may not resolve correctly in clock group expressions.

#-------------------------------------------------------------------
# Primary input clocks
#-------------------------------------------------------------------
create_clock -period 20.000 -name clk_50m_in [get_ports clk_50m_in]
create_clock -period 8.000  -name rgmii_rxc  [get_ports rgmii_rxc]

# GT reference clock (125MHz differential)
create_clock -period 8.000 -name gtrefclk [get_ports gtrefclk_p]

#-------------------------------------------------------------------
# MDIO clock (2.5MHz, generated from 50MHz PLL via divider)
#-------------------------------------------------------------------
create_generated_clock -name mdio_clk_eth0 \
    -source [get_ports clk_50m_in] \
    -divide_by 20 \
    [get_pins u_webserver/u_lcpu_mdio_eth0/u_clock_frequency_divider/clk_out_reg/Q]

#-------------------------------------------------------------------
# GTPE2_CHANNEL placement constraints
#-------------------------------------------------------------------
# SFP1 (eth1) uses MGT_RX0/TX0 → GTPE2_CHANNEL_X0Y0
set_property LOC GTPE2_CHANNEL_X0Y0 [get_cells -hier -filter {NAME =~ *u_sfp_wrapper/pcs_pma_eth1/*/gtpe2_i}]

# SFP2 (eth2) uses MGT_RX1/TX1 → GTPE2_CHANNEL_X0Y1
set_property LOC GTPE2_CHANNEL_X0Y1 [get_cells -hier -filter {NAME =~ *u_sfp_wrapper/pcs_pma_eth2/*/gtpe2_i}]

#-------------------------------------------------------------------
# Generated clocks: SGMII MMCM outputs
#-------------------------------------------------------------------
# SGMII userclk2 (125MHz) — from GT TXOUTCLK via MMCM CLKOUT0
create_generated_clock -name sgmii_userclk2 \
    -source [get_pins u_sfp_wrapper/core_clocking_i/mmcm_adv_inst/CLKIN1] \
    -divide_by 1 \
    [get_pins u_sfp_wrapper/core_clocking_i/mmcm_adv_inst/CLKOUT0]

# SGMII userclk (62.5MHz) — from GT TXOUTCLK via MMCM CLKOUT1
create_generated_clock -name sgmii_userclk \
    -source [get_pins u_sfp_wrapper/core_clocking_i/mmcm_adv_inst/CLKIN1] \
    -divide_by 2 \
    [get_pins u_sfp_wrapper/core_clocking_i/mmcm_adv_inst/CLKOUT1]

# Bootloader SPI clock (5MHz). Generated by clock_frequency_divider instance
# u_spi_clk_div (same module as lcpu_sflash), clocked by c0_pll_50m via
# clk_50mhz. Source = register clock pin (clk_out_reg/C), target = clk_out_reg/Q.
create_generated_clock -name spi_clk_bl \
    -source [get_pins u_webserver/u_spi_clk_div/clk_out_reg/C] \
    -divide_by 10 \
    [get_pins u_webserver/u_spi_clk_div/clk_out_reg/Q]

#-------------------------------------------------------------------
# Async clock groups (fallback — explicit false_path below is primary)
#-------------------------------------------------------------------
set_clock_groups -asynchronous \
    -group [get_clocks clk_50m_in] \
    -group [get_clocks c0_pll_50m] \
    -group [get_clocks c1_pll_50m] \
    -group [get_clocks c2_pll_50m] \
    -group [get_clocks rgmii_rxc] \
    -group [get_clocks gtrefclk] \
    -group [get_clocks sgmii_userclk] \
    -group [get_clocks sgmii_userclk2]

#-------------------------------------------------------------------
# RGMII TX output delay
#-------------------------------------------------------------------
set_output_delay -clock [get_clocks -of_objects [get_ports rgmii_txc]] \
    -max 1.000 [get_ports {rgmii_txd[*] rgmii_tx_ctl}]
set_output_delay -clock [get_clocks -of_objects [get_ports rgmii_txc]] \
    -min 0.000 [get_ports {rgmii_txd[*] rgmii_tx_ctl}]

#-------------------------------------------------------------------
# RGMII RX input delay
#-------------------------------------------------------------------
set_input_delay -clock rgmii_rxc -max 2.500 [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]
set_input_delay -clock rgmii_rxc -min 2.500 [get_ports {rgmii_rxd[*] rgmii_rx_ctl}]

#-------------------------------------------------------------------
# UART
#-------------------------------------------------------------------
set_input_delay -clock c0_pll_50m -max 5.000 [get_ports uart_rx]
set_input_delay -clock c0_pll_50m -min 1.000 [get_ports uart_rx]
set_output_delay -clock c0_pll_50m -max 5.000 [get_ports uart_tx]
set_output_delay -clock c0_pll_50m -min 1.000 [get_ports uart_tx]

#-------------------------------------------------------------------
# MDIO
#-------------------------------------------------------------------
set_output_delay -clock mdio_clk_eth0 -max 5.000 [get_ports eth0_mdc]
set_output_delay -clock mdio_clk_eth0 -min 1.000 [get_ports eth0_mdc]
set_output_delay -clock mdio_clk_eth0 -max 5.000 [get_ports eth0_mdio]
set_output_delay -clock mdio_clk_eth0 -min 1.000 [get_ports eth0_mdio]
set_input_delay  -clock mdio_clk_eth0 -max 5.000 [get_ports eth0_mdio]
set_input_delay  -clock mdio_clk_eth0 -min 1.000 [get_ports eth0_mdio]

#-------------------------------------------------------------------
# Misc slow outputs
#-------------------------------------------------------------------
set_output_delay -clock c0_pll_50m \
    -max 10.000 [get_ports {rgmii_reset_l led_o[*] sfp1_tx_disable sfp2_tx_disable}]
set_output_delay -clock c0_pll_50m \
    -min 0.000 [get_ports {rgmii_reset_l led_o[*] sfp1_tx_disable sfp2_tx_disable}]

#-------------------------------------------------------------------
# QSPI Flash (SPI mode, ~5MHz SCK from clock divider)
#
# Fix: Reduced output delay from 10ns to 6ns.
#   The flash SPI runs at ~5MHz (200ns period), so 6ns output delay
#   (PCB trace + flash device setup time) is the real external requirement.
#   The original 10ns was too aggressive given the data path through
#   CARRY4+LUT+OBUF (~8.2ns logic + 3.3ns OBUF) on a 20ns clock period.
#-------------------------------------------------------------------
set_output_delay -clock c0_pll_50m \
    -max 6.000 [get_ports {flash_cs_n flash_mosi flash_wp_n flash_rst_n}]
set_output_delay -clock c0_pll_50m \
    -min 0.000 [get_ports {flash_cs_n flash_mosi flash_wp_n flash_rst_n}]
set_input_delay -clock c0_pll_50m \
    -max 10.000 [get_ports flash_miso]
set_input_delay -clock c0_pll_50m \
    -min 1.000 [get_ports flash_miso]

#===================================================================
# CDC false paths — explicit per-pair (primary mechanism)
#
# These false paths are the PRIMARY way to cut inter-clock timing.
# They cover ALL paths between async clock domains, including:
#   - register-to-register CDC paths (async FIFO, gray-code sync)
#   - output port paths where set_output_delay references a PLL clock
#     but the source register is in a different clock domain
#   - recovery/removal checks on async reset/preset pins
#===================================================================

#-------------------------------------------------------------------
# Async reset input port
#-------------------------------------------------------------------
set_false_path -through [get_ports reset_l]

#-------------------------------------------------------------------
# 1. clk_50m_in ↔ PLL output clocks (c0/c1/c2)
#
# The reset controller (u_clk_rst_ctrl) runs on clk_50m_in and
# produces reset_l_synced used as async reset/preset in all PLL
# clock domains. These are legitimate CDC paths via synchronizers.
# Also covers output ports (rgmii_reset_l) where output delay
# references a PLL clock but source register is in clk_50m_in domain.
#-------------------------------------------------------------------
set_false_path -from [get_clocks clk_50m_in] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks clk_50m_in]
set_false_path -from [get_clocks clk_50m_in] -to [get_clocks c1_pll_50m]
set_false_path -from [get_clocks c1_pll_50m] -to [get_clocks clk_50m_in]
set_false_path -from [get_clocks clk_50m_in] -to [get_clocks c2_pll_50m]
set_false_path -from [get_clocks c2_pll_50m] -to [get_clocks clk_50m_in]

#-------------------------------------------------------------------
# 2. RGMII RX clock ↔ PLL output clocks (c0/c1/c2)
#
# eth0 RGMII RX data arrives in rgmii_rxc domain and crosses into
# system clock domains via async FIFOs (u_rx_asyncfifo) and
# gray-code synchronizers (g_sync_eth0_stats).
#-------------------------------------------------------------------
set_false_path -from [get_clocks rgmii_rxc] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks rgmii_rxc]
set_false_path -from [get_clocks rgmii_rxc] -to [get_clocks c1_pll_50m]
set_false_path -from [get_clocks c1_pll_50m] -to [get_clocks rgmii_rxc]
set_false_path -from [get_clocks rgmii_rxc] -to [get_clocks c2_pll_50m]
set_false_path -from [get_clocks c2_pll_50m] -to [get_clocks rgmii_rxc]

#-------------------------------------------------------------------
# 3. clk_50m_in ↔ RGMII RX clock
#-------------------------------------------------------------------
set_false_path -from [get_clocks clk_50m_in] -to [get_clocks rgmii_rxc]
set_false_path -from [get_clocks rgmii_rxc] -to [get_clocks clk_50m_in]

#-------------------------------------------------------------------
# 4. SGMII clocks ↔ PLL 125MHz (c1_pll_50m)
#
# SGMII core (sgmii_userclk2/userclk) crosses into system packet
# processing domain (c1_pll_50m) via GMII interface FIFOs.
#-------------------------------------------------------------------
set_false_path -from [get_clocks sgmii_userclk2] -to [get_clocks c1_pll_50m]
set_false_path -from [get_clocks c1_pll_50m] -to [get_clocks sgmii_userclk2]
set_false_path -from [get_clocks sgmii_userclk] -to [get_clocks c1_pll_50m]
set_false_path -from [get_clocks c1_pll_50m] -to [get_clocks sgmii_userclk]

#-------------------------------------------------------------------
# 4b. SGMII clocks ↔ system 50MHz (c0_pll_50m)
#
# 2026-08-31 时序修复(原 -7.05ns / 26 端点):
#   a) Xilinx PCS/PMA 核内部配置/复位路径(RUDI/MGT_RESET/comma align)
#      —— 准静态配置信号, IP 惯例 false_path;
#   b) sfp_link_dbg/sfp_status_dbg 状态位 —— RTL 已补逐位 2FF 同步器
#      (webserver_wrapper.v), false_path 覆盖同步器第一级跨域路径。
#-------------------------------------------------------------------
set_false_path -from [get_clocks sgmii_userclk2] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks sgmii_userclk2]
set_false_path -from [get_clocks sgmii_userclk] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks sgmii_userclk]

#-------------------------------------------------------------------
# 9. fpga_ila 核寄存器总线 (hub → 各核 rdata 采集)
#
# 2026-08-31 时序修复(原 -2.50ns / 32 端点, c1 域内):
# hub 访问一次寄存器跨越整段 UART 传输(微秒级), addr 在采样前由
# 协议保证长期稳定 —— 该总线为准静态, 无需单周期 8ns 收敛。
# 用 set_max_delay -datapath_only 封顶而非 false_path, 保留
# 慢速采样语义。
#-------------------------------------------------------------------
set_max_delay -datapath_only 16.000 \
    -from [get_cells -hier -filter {NAME =~ *u_ila_debug*core_reg_*_reg*}] \
    -to   [get_cells -hier -filter {NAME =~ *g_core.u_ela/*rdata_reg*}]

#-------------------------------------------------------------------
# 5. GT refclk ↔ PLL 200MHz (c2_pll_50m)
#-------------------------------------------------------------------
set_false_path -from [get_clocks gtrefclk] -to [get_clocks c2_pll_50m]
set_false_path -from [get_clocks c2_pll_50m] -to [get_clocks gtrefclk]

#-------------------------------------------------------------------
# 6. Bootloader SPI clock (5MHz) ↔ system 50MHz (c0_pll_50m)
#-------------------------------------------------------------------
set_false_path -from [get_clocks spi_clk_bl] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks spi_clk_bl]

#-------------------------------------------------------------------
# 7. MDIO clock (2.5MHz) ↔ system 50MHz (c0_pll_50m)
#-------------------------------------------------------------------
set_false_path -from [get_clocks mdio_clk_eth0] -to [get_clocks c0_pll_50m]
set_false_path -from [get_clocks c0_pll_50m] -to [get_clocks mdio_clk_eth0]

#-------------------------------------------------------------------
# 8. JTAG/DBG_HUB TCK ↔ system clocks
#-------------------------------------------------------------------
set_false_path -from [get_clocks clk_50m_in] \
    -to [get_clocks dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_inst/SERIES7_BSCAN.bscan_inst/TCK]
set_false_path -from [get_clocks dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_inst/SERIES7_BSCAN.bscan_inst/TCK] \
    -to [get_clocks clk_50m_in]
set_false_path -from [get_clocks c0_pll_50m] \
    -to [get_clocks dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_inst/SERIES7_BSCAN.bscan_inst/TCK]
set_false_path -from [get_clocks dbg_hub/inst/BSCANID.u_xsdbm_id/SWITCH_N_EXT_BSCAN.bscan_inst/SERIES7_BSCAN.bscan_inst/TCK] \
    -to [get_clocks c0_pll_50m]
